# Site settings
title: "BIGDATAPUMP/TECH"
email: 
description: Tech blog BDP
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bigdatapump.github.io" # the base hostname & protocol for your site
twitter_username: bigdatapump
github_username: bigdatapump

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
